// Single source of truth for all preparedness tasks.
// IDs are numeric to match PrepareScreen's task list and completedTasks tracking.

export const PREPAREDNESS_TASKS = [
  {
    id: 1,
    title: 'Flood Safety Quiz',
    description: 'Test your knowledge of flood safety and what to do during a flood',
    type: 'quiz',
    points: 30,
    category: 'awareness',
    difficulty: 'beginner',
    questions: 10,
    duration: 5,
    featured: true,
  },
  {
    id: 2,
    title: 'First Aid Essentials',
    description: 'Learn the fundamentals of first aid in emergency situations',
    type: 'quiz',
    points: 50,
    category: 'skills',
    difficulty: 'intermediate',
    questions: 10,
    duration: 7,
  },
  {
    id: 3,
    title: 'CPR Skills',
    description: 'Step-by-step guide to performing CPR correctly',
    type: 'skill',
    points: 75,
    category: 'skills',
    difficulty: 'intermediate',
    duration: 15,
    interactive: true,
  },
  {
    id: 4,
    title: 'Emergency Kit Check',
    description: 'Assemble and verify your emergency kit has all essential supplies',
    type: 'task',
    points: 40,
    category: 'preparation',
    difficulty: 'beginner',
    duration: 10,
  },
  {
    id: 5,
    title: 'Evacuation Route Planning',
    description: 'Map out two evacuation routes from your home',
    type: 'task',
    points: 45,
    category: 'planning',
    difficulty: 'beginner',
    duration: 12,
  },
  {
    id: 6,
    title: 'Earthquake Preparedness',
    description: 'Learn how to stay safe before, during, and after an earthquake',
    type: 'quiz',
    points: 35,
    category: 'awareness',
    difficulty: 'beginner',
    questions: 8,
    duration: 6,
  },
  {
    id: 7,
    title: 'Fire Safety Basics',
    description: 'Essential fire safety skills including escape planning and extinguisher use',
    type: 'skill',
    points: 60,
    category: 'skills',
    difficulty: 'beginner',
    duration: 10,
    interactive: true,
  },
  {
    id: 8,
    title: 'Storm Preparation',
    description: 'Prepare your home and family for severe storms',
    type: 'task',
    points: 35,
    category: 'preparation',
    difficulty: 'beginner',
    duration: 8,
  },
  {
    id: 9,
    title: 'Hurricane Preparedness',
    description: 'Know what to do before, during, and after a hurricane',
    type: 'quiz',
    points: 40,
    category: 'awareness',
    difficulty: 'intermediate',
    questions: 8,
    duration: 6,
  },
  {
    id: 10,
    title: 'Wildfire Safety',
    description: 'Understand wildfire behaviour and how to protect yourself',
    type: 'quiz',
    points: 40,
    category: 'awareness',
    difficulty: 'intermediate',
    questions: 8,
    duration: 6,
  },
  {
    id: 11,
    title: 'Tornado Safety',
    description: 'Learn the warning signs and safest actions during a tornado',
    type: 'quiz',
    points: 35,
    category: 'awareness',
    difficulty: 'beginner',
    questions: 8,
    duration: 5,
  },
  {
    id: 12,
    title: 'Choking Response',
    description: 'Step-by-step guide to helping a choking adult or child',
    type: 'skill',
    points: 70,
    category: 'skills',
    difficulty: 'intermediate',
    duration: 12,
    interactive: true,
  },
  {
    id: 13,
    title: 'Severe Bleeding Control',
    description: 'How to safely control severe bleeding while waiting for help',
    type: 'skill',
    points: 70,
    category: 'skills',
    difficulty: 'intermediate',
    duration: 15,
    interactive: true,
  },
  {
    id: 14,
    title: 'Burn Treatment',
    description: 'Correct first aid for minor and serious burns',
    type: 'skill',
    points: 65,
    category: 'skills',
    difficulty: 'beginner',
    duration: 10,
    interactive: true,
  },
];

export const TOTAL_TASKS = PREPAREDNESS_TASKS.length; // 14

export const BADGES = [
  {
    id: 'badge_beginner',
    title: 'Getting Started',
    description: 'Complete your first task',
    requirement: 1,
  },
  {
    id: 'badge_halfway',
    title: 'Halfway There',
    description: 'Complete 7 tasks',
    requirement: 7,
  },
  {
    id: 'badge_prepared',
    title: 'Well Prepared',
    description: 'Complete 10 tasks',
    requirement: 10,
  },
  {
    id: 'badge_expert',
    title: 'Preparedness Expert',
    description: 'Complete all 14 tasks',
    requirement: TOTAL_TASKS,
  },
  {
    id: 'badge_points_500',
    title: 'Point Master',
    description: 'Earn 500 points',
    requirement: 500,
  },
];